Common/Estimate.h (swap): Add noexcept
Fix error with clang.

Common/Estimate.h:177:14: error:
'swap<EstimateRecord>' is missing exception specification
'noexcept(is_nothrow_move_constructible<EstimateRecord>::value &&
is_nothrow_move_assignable<EstimateRecord>::value)'
inline void swap(EstimateRecord&, EstimateRecord&)